# .github/workflows/daily_run.yml
# JAVÍTVA (V1.2) - Hozzáadva az admin értesítő feladat ('send_admin_alert')

name: Napi Tippgenerálás és Adatgyűjtés

on:
  workflow_dispatch: # Manuális indítás gomb
  schedule:
    # Futtatás minden nap 09:00 UTC-kor (ami 10:00 CET)
    - cron: '0 9 * * *'

jobs:
  # 1. FELADAT: Adat-pillanatkép készítése a backtesthez
  run_snapshot_exporter:
    runs-on: ubuntu-latest
    
    # Engedélyt adunk ennek a feladatnak, hogy írjon a repositoryba (git push)
    permissions:
      contents: write

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Pillanatkép adatok generálása (V3.0)
        run: python gemini_data_exporter.py # Futtatjuk a V3.0-ás adatgyűjtőt
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

      - name: Változások feltöltése a repositoryba
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@github.com'
          # Csak az új snapshot mappát adjuk hozzá
          git add backtest_snapshots/snapshot_data_*.json
          # Ellenőrizzük, van-e mit commmitelni (ha már létezett a fájl, ne hibázzon)
          git diff --staged --quiet || git commit -m "Automatikus backtest pillanatkép mentése"
          git push

  # 2. FELADAT: Éles tippek generálása (NEM küld, csak adatbázisba ír)
  generate_tips_to_db:
    runs-on: ubuntu-latest
    needs: run_snapshot_exporter # Megvárja az adatgyűjtést
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Tippek generálása adatbázisba (V17.8)
        run: python tipp_generator.py # Futtatjuk az új V17.8-as, "csak holnapi" generátort
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          # A Telegram titkok ide már nem kellenek, de nem ártanak
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} 
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}

  # 3. FELADAT: Admin értesítés küldése (EZ VOLT A HIÁNYZÓ LÉPÉS)
  send_admin_alert:
    runs-on: ubuntu-latest
    needs: generate_tips_to_db # Megvárja, amíg a tippek az adatbázisba kerültek
    
    # Csak akkor fusson le, ha a futtatás nem "teszt" (pl. nem manuális teszt)
    # Ezt a feltételt egyelőre kivesszük, hogy manuális futtatásnál is tesztelhető legyen
    # if: github.event_name == 'schedule' 

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Admin értesítés küldése a "Jóváhagyásra vár" státuszról
        run: python send_admin_summary.py # Ez a szkript küldi az üzenetet
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
