# .github/workflows/daily_run.yml
# Ez a workflow egyesíti az adatgyűjtést (V3.0) és a tippgenerálást (V17.8)
# Töröld a 'generate-and-notify.yml' és 'generate-gemini-data.yml' fájlokat, hogy ez lépjen a helyükre.

name: Napi Tippgenerálás és Adatgyűjtés

on:
  workflow_dispatch: # Manuális indítás gomb
  schedule:
    # Futtatás minden nap 09:00 UTC-kor (ami 10:00 CET - Közép-Európai Téli Idő)
    # Figyelem: Nyári időszámítás (CEST) alatt ez 11:00-kor fog futni.
    # Ha fixen 10:00-kor szeretnéd Budapest idő szerint, akkor '0 8 * * *' (CEST) és '0 9 * * *' (CET) kellene,
    # de a GitHub Actions nem kezeli az időzónaváltást. A 09:00 UTC (10:00 CET) egy stabil pont.
    - cron: '0 9 * * *'

jobs:
  # 1. FELADAT: Adat-pillanatkép készítése a backtesthez
  run_snapshot_exporter:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Vagy amilyen verziót használsz

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Adat-pillanatkép generálása (V3.0)
        run: python gemini_data_exporter.py # Futtatjuk az új V3.0-ás adatgyűjtőt
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          # A SUPABASE kulcsok ide nem kellenek, mert ez a szkript csak fájlba ír

      - name: Módosítások feltöltése (Commit) a backtest_snapshots mappába
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          # Csak az új snapshot mappát adjuk hozzá
          git add backtest_snapshots/snapshot_data_*.json
          # Ellenőrizzük, van-e mit commmitelni (ha már létezett a fájl, ne hibázzon)
          git diff --staged --quiet || git commit -m "Automatikus backtest pillanatkép mentése"
          git push

  # 2. FELADAT: Éles tippek generálása és küldése
  generate_and_notify_tips:
    runs-on: ubuntu-latest
    needs: run_snapshot_exporter # Ez a sor biztosítja, hogy csak az adatmentés UTÁN fusson le!
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Tippek generálása és küldése (V17.8)
        run: python tipp_generator.py # Futtatjuk az új V17.8-as, "csak holnapi" generátort
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_ADMIN_CHAT_ID: ${{ secrets.TELEGRAM_ADMIN_CHAT_ID }}
          # A 'DATABASE_URL' és 'FLASK_SECRET_KEY' nem szükséges ehhez a szkripthez
