# .github/workflows/daily_run.yml
# JAVÍTVA (V1.3) - Hozzáadva a hiányzó Telegram titkok a 'send_admin_alert' feladathoz

name: Napi Tippgenerálás és Adatgyűjtés

on:
  workflow_dispatch: # Manuális indítás gomb
  schedule:
    # Futtatás minden nap 09:00 UTC-kor (ami 10:00 CET)
    - cron: '0 9 * * *'

jobs:
  # 1. FELADAT: Adat-pillanatkép készítése a backtesthez
  run_snapshot_exporter:
    runs-on: ubuntu-latest
    
    # Engedélyt adunk ennek a feladatnak, hogy írjon a repositoryba (git push)
    permissions:
      contents: write

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Pillanatkép adatok generálása (V3.0)
        run: python gemini_data_exporter.py
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

      - name: Változások feltöltése a repositoryba
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@github.com'
          git add backtest_snapshots/snapshot_data_*.json
          git diff --staged --quiet || git commit -m "Automatikus backtest pillanatkép mentése"
          git push

  # 2. FELADAT: Éles tippek generálása (NEM küld, csak adatbázisba ír)
  generate_tips_to_db:
    runs-on: ubuntu-latest
    needs: run_snapshot_exporter # Megvárja az adatgyűjtést
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Tippek generálása adatbázisba (V17.8)
        run: python tipp_generator.py
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }} # Ide is kell az admin ID, hogy a generátor naplózni tudja a hibákat
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} # Ide is kell

  # 3. FELADAT: Admin értesítés küldése
  send_admin_alert:
    runs-on: ubuntu-latest
    needs: generate_tips_to_db # Megvárja, amíg a tippek az adatbázisba kerültek
    
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Admin értesítés küldése a "Jóváhagyásra vár" státuszról
        run: python send_admin_summary.py # Ez a szkript küldi az üzenetet
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          # --- EZ A KÉT SOR HIÁNYZOTT ---
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
          # --- JAVÍTÁS VÉGE ---
