name: Eredmeny Ellenorzes

on:
  schedule:
    - cron: '0 * * * *' # Minden órában
  workflow_dispatch:

jobs:
  check-results:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Függőségek telepítése (Javított)
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Eredmények ellenőrzése
        run: python eredmeny_ellenorzo.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
