name: Admin Teszt Futtatas

on:
  workflow_dispatch:

jobs:
  admin-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Függőségek telepítése
        run: python -m pip install -r requirements.txt
      
      - name: Tippek generálása (teszt üzemmódban)
        id: generate_tips
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python tipp_generator.py

      - name: Admin összefoglaló küldése
        # Ez a lépés mindig lefut, hogy tájékoztasson az eredményről
        if: always()
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python send_admin_summary.py
