name: Napi Tippek Generalasa es Ertesites

on:
  schedule:
    # Minden este 17:00 UTC-kor fut le (ez 19:00 nyáron, 18:00 télen Magyarországon)
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  generate-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Tippek generálása
        id: generate_step # Ez az ID fontos a hivatkozáshoz
        run: python tipp_generator.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

      - name: Értesítések kiküldése
        # Csak akkor fut le, ha a 'generate_step' lépés 'TIPS_FOUND' kimenete 'true'
        if: steps.generate_step.outputs.TIPS_FOUND == 'true'
        run: python send_notification.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
