name: Napi Tippek Generalasa es Ertesites

on:
  schedule:
    # Minden este 20:00 UTC-kor fut le (ez 22:00 nyáron, 21:00 télen Magyarországon)
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  generate-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Tippek generálása
        id: generate_step # Lépés azonosítója
        run: python tipp_generator.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

      - name: Értesítések kiküldése (ha a generálás sikeres volt)
        if: success()
        run: python send_notification.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
