# .github/workflows/tipp_generalas.yml

name: Napi Tippek Generalasa

on:
  schedule:
    # Minden nap hajnali 3-kor (UTC) fut le
    - cron: '0 3 * * *'
  workflow_dispatch: # Engedélyezi a manuális indítást is

jobs:
  generate-tips:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          pip install supabase requests python-dotenv

      - name: Tippek generálása és mentése
        run: python tipp_generator.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
